/**
 * Sanity bands for every committed chart set (`charts/4`, A2c-A2d; docs/CHARTS.md
 * §6, §8). `data.test.ts` holds the 6-max 100bb set to `charts/2`'s bands;
 * here every set - 6-max at 40-200bb, 9-max at 100-200bb - is held to the
 * properties any sane chart has, whatever its table and depth, plus the ones
 * that relate the sets to each other. Bands are wide on purpose and come from
 * general poker theory, never from a published chart:
 *
 *  - every frequency vector sums to 1; EVs are consistent with frequencies
 *    (the chart's mix loses at most 2% of the pot to the best action for a
 *    class in range; off-range classes play their best response);
 *  - AA never folds; KK never folds before an all-in where it is in range
 *    (except cold, where the tree offers only fold or re-raise, and against
 *    two re-raisers); 72o never opens first in;
 *  - raise-first-in widens with position (strictly from the LJ / UTG of
 *    6-max on), the small blind continues 35-75% first in, the big blind
 *    defends 40-80% against a button open;
 *  - 9-max's three earliest seats open tighter than 6-max's first seat at
 *    the same depth, and 9-max's LJ - the same distance from the button as
 *    6-max's UTG - opens within a few points of it;
 *  - the sizes recorded per depth: 2.2bb opens at 40bb, and 4-bets all-in
 *    past 40% of the stack;
 *  - the generator's convergence: NashConv under 1 mbb/hand (2 for 9-max).
 */

import { statSync } from "node:fs";
import { describe, expect, it } from "vitest";

import {
  CHART_SETS,
  chartTree,
  IN_RANGE,
  isOpenLimpNode,
  MAX_SELF_LOSS,
  type ChartSet,
} from "../../../frontend/src/lib/charts/index.js";
import { walkLine } from "../../../frontend/src/lib/analysis/reports.js";
import { CLASS_COMBOS, classByName, NUM_CLASSES } from "../../../frontend/src/lib/solver/index.js";
import { chartSet, fileOf } from "./support.js";

const H = NUM_CLASSES;

/** Share of the actor's range (combo- and reach-weighted) that does not fold. */
function continues(set: ChartSet, line: string): number {
  const node = set.nodes.get(line);
  if (!node) throw new Error(`${set.id}: no node ${JSON.stringify(line)}`);
  const fold = node.options.findIndex((o) => o.action === "fold");
  let sum = 0;
  let total = 0;
  for (let i = 0; i < H; i += 1) {
    const w = CLASS_COMBOS[i] * node.range[i];
    sum += w * (fold < 0 ? 1 : 1 - node.freq[fold * H + i]);
    total += w;
  }
  return sum / total;
}

/** RFI widths of the seats before the big blind, in action order. */
function rfi(set: ChartSet): { seat: string; width: number }[] {
  return set.game.positions.slice(0, -1).map((seat, k) => ({ seat, width: continues(set, "f".repeat(k)) }));
}

/**
 * Distinct players who raised on a line: three is an open, a 3-bet and a cold
 * 4-bet by a third player - the opener facing two re-raisers may fold KK
 * (one of them holds AA often enough), as a cold player may in 6-max.
 */
function raisers(line: string, set: ChartSet): number {
  return new Set(walkLine(line, set.game.positions).steps.filter((s) => s.code === "r" || s.code === "a").map((s) => s.position)).size;
}

/** The big blind's node facing a button open, the small blind folding. */
function bbVsBtn(set: ChartSet): string {
  return "f".repeat(set.game.positions.indexOf("BTN")) + "rf";
}

describe.each(CHART_SETS.map((spec) => [spec.id, spec] as const))("%s", (id, spec) => {
  const set = chartSet(id);
  const model = set.model as Record<string, any>;

  it("is the set the registry lists, generated by our solver with a fitted realisation model", () => {
    expect(set.id).toBe(id);
    expect(set.version).toBe("charts/4");
    expect(set.game.positions).toHaveLength(spec.players);
    expect(set.game.stackBb).toBe(spec.stackBb);
    expect(model.hash).toMatch(/^[0-9a-f]{8}$/);
    expect(model.realisation.name).toMatch(/solver-fit/);
    expect(model.realisationFit.rounds.length).toBeGreaterThanOrEqual(2);
    // charts/4 solves the limp tree once on the set's own committed fit (docs/CHARTS.md §6.7).
    expect(model.realisationFit.reusedBy).toMatch(/charts\/4/);
    expect(model.rake.percent).toBe(0.05);
    expect(model.solver.iterations).toBeGreaterThanOrEqual(3000);
    expect(set.nodes.size).toBeGreaterThan(150);
    expect(statSync(fileOf(id)).size).toBeLessThan(spec.players === 9 ? 9_000_000 : 3_000_000);
  });

  it("recorded good convergence", () => {
    expect(model.convergence.nashConvMbb).toBeLessThan(spec.players === 9 ? 2 : 1);
    const history = model.convergence.history as { nashConvMbb: number }[];
    expect(history[history.length - 1].nashConvMbb).toBeLessThan(history[0].nashConvMbb);
  });

  it("has frequencies that sum to 1, and EVs consistent with them", () => {
    let checked = 0;
    for (const n of set.nodes.values()) {
      const count = n.options.length;
      expect(n.freq).toHaveLength(count * H);
      const tolerance = MAX_SELF_LOSS * n.potBb + 0.02;
      for (let i = 0; i < H; i += 1) {
        let sum = 0;
        let best = -Infinity;
        for (let a = 0; a < count; a += 1) {
          sum += n.freq[a * H + i];
          best = Math.max(best, n.ev[a * H + i]);
        }
        expect(sum, `${n.line} class ${i}`).toBeCloseTo(1, 9);
        if (n.range[i] >= IN_RANGE) {
          let loss = 0;
          for (let a = 0; a < count; a += 1) loss += n.freq[a * H + i] * (best - n.ev[a * H + i]);
          expect(loss, `${JSON.stringify(n.line)} class ${i}`).toBeLessThanOrEqual(tolerance);
          checked += 1;
        } else if (n.range[i] === 0) {
          const played = n.options.findIndex((_, a) => n.freq[a * H + i] === 1);
          expect(n.ev[played * H + i]).toBeGreaterThanOrEqual(best - 0.011);
        }
      }
    }
    expect(checked).toBeGreaterThan(2000);
  });

  it("never folds AA, keeps KK before an all-in, never opens 72o first in", () => {
    const aa = classByName("AA");
    const kk = classByName("KK");
    const tree = chartTree(set);
    for (const n of set.nodes.values()) {
      const fold = n.options.findIndex((o) => o.action === "fold");
      if (fold < 0) continue;
      expect(n.freq[fold * H + aa], `AA folds at ${JSON.stringify(n.line)}`).toBe(0);
      // Cold (the tree offers only fold or re-raise) or against two re-raisers, KK may fold.
      if (n.range[kk] <= 0.01 || n.cold || (n.scenario === "vs-4bet" && raisers(n.line, set) >= 3)) continue;
      // Behind an open limp, below the usual 1e-5 of hands (kept for grading, charts/4), a
      // re-raiser's range can be a class or two: facing AA alone, KK folds.
      if (isOpenLimpNode(n) && n.reach < 1e-5) continue;
      // Facing an all-in (a 5-bet, or a 4-bet shove at 40bb) KK may be close to indifferent multiway.
      const at = tree.lineIndex.get(n.line) as number;
      const facingAllIn = tree.toMatch[at] >= tree.stackBb;
      if (!facingAllIn) expect(n.freq[fold * H + kk], `KK folds at ${JSON.stringify(n.line)}`).toBeLessThan(0.01);
    }
    const first = set.nodes.get("") as NonNullable<ReturnType<typeof set.nodes.get>>;
    const open = first.options.findIndex((o) => o.action === "raise");
    expect(first.freq[open * H + classByName("72o")]).toBe(0);
    // Every class keeps the limp's tremble (0.5%): AA opens all the rest.
    expect(first.freq[open * H + aa]).toBeGreaterThan(0.95);
  });

  it("opens wider in later position, and defends the blinds plausibly", () => {
    const widths = rfi(set);
    const seats = widths.filter((w) => w.seat !== "SB");
    for (let k = 1; k < seats.length; k += 1) {
      // The earliest full-ring seats are within a point of each other; from 6-max's UTG on, strictly wider.
      expect(seats[k].width, `${seats[k].seat} vs ${seats[k - 1].seat}`).toBeGreaterThan(seats[k - 1].width - 0.01);
    }
    for (const seat of ["LJ", "HJ", "CO", "BTN"]) {
      const k = seats.findIndex((w) => w.seat === seat);
      if (k > 0 && (seat !== "LJ" || spec.players === 9)) expect(seats[k].width).toBeGreaterThan(seats[k - 1].width);
    }
    expect(seats[0].width).toBeGreaterThan(spec.players === 9 ? 0.06 : 0.1);
    expect(seats[0].width).toBeLessThan(0.22);
    const btn = widths.find((w) => w.seat === "BTN")?.width as number;
    expect(btn).toBeGreaterThan(0.3);
    expect(btn).toBeLessThan(0.6);
    const sb = widths.find((w) => w.seat === "SB")?.width as number;
    expect(sb).toBeGreaterThan(0.35);
    expect(sb).toBeLessThan(0.75);
    // Wider at 40bb, where the open is 2.2bb and the price better.
    const bb = continues(set, bbVsBtn(set));
    expect(bb).toBeGreaterThan(0.4);
    expect(bb).toBeLessThan(0.8);
  });
});

/** Share of the actor's range (combo- and reach-weighted) taking one of `actions` at a node. */
function share(set: ChartSet, line: string, actions: readonly string[]): number {
  const node = set.nodes.get(line);
  if (!node) throw new Error(`${set.id}: no node ${JSON.stringify(line)}`);
  let sum = 0;
  let total = 0;
  for (let i = 0; i < H; i += 1) {
    const w = CLASS_COMBOS[i] * node.range[i];
    total += w;
    node.options.forEach((o, a) => {
      if (actions.includes(o.action)) sum += w * node.freq[a * H + i];
    });
  }
  return sum / total;
}
const ISO = ["raise", "allin"];

describe.each(CHART_SETS.map((spec) => [spec.id, spec] as const))("%s: limped pots (charts/4)", (id) => {
  const set = chartSet(id);
  const seats = set.game.positions;
  const tree = (set.model as Record<string, any>).tree;
  const limpNodes = [...set.nodes.values()].filter((n) => isOpenLimpNode(n));
  /** The line where `seat` faces a limp by `limper`, everyone else folding. */
  const vsLimp = (limper: number, seat: number) => "f".repeat(limper) + "c" + "f".repeat(seat - limper - 1);

  it("records the limp tree and keeps nodes behind limps", () => {
    expect(tree.maxLimpers).toBe(3);
    expect(tree.limpFloor).toBeGreaterThan(0);
    expect(limpNodes.length).toBeGreaterThan(100);
    expect(limpNodes.some((n) => n.scenario === "vs-iso")).toBe(true);
    expect(limpNodes.some((n) => n.limpers.length === 3)).toBe(true);
    // The equilibrium itself rarely limps first in outside the small blind: the tremble and little more.
    for (let k = 0; k < seats.length - 2; k += 1) expect(share(set, "f".repeat(k), ["call"]), seats[k]).toBeLessThan(0.05);
  });

  it("isolates more often in later position, against the same limper", () => {
    const btn = seats.indexOf("BTN");
    const first = 0;
    const widths = [];
    for (let seat = first + 1; seat <= btn; seat += 1) widths.push(share(set, vsLimp(first, seat), ISO));
    for (let k = 1; k < widths.length; k += 1) expect(widths[k], `${seats[k + 1]} vs ${seats[k]}`).toBeGreaterThan(widths[k - 1] - 0.03);
    expect(widths[widths.length - 1]).toBeGreaterThan(widths[0]);
    // ... and more often against a later (wider-limping, in practice) limper: the button against the cutoff.
    expect(share(set, vsLimp(btn - 1, btn), ISO)).toBeGreaterThan(share(set, vsLimp(first, btn), ISO) - 0.02);
  });

  it("isolates with premium hands, folds the worst, and the big blind checks behind with most of its range", () => {
    const aa = classByName("AA");
    const kk = classByName("KK");
    const seven2 = classByName("72o");
    for (const n of limpNodes) {
      if (n.scenario !== "vs-limp") continue;
      const raise = n.options.findIndex((o) => ISO.includes(o.action));
      expect(n.freq[raise * H + aa], `AA at ${JSON.stringify(n.line)}`).toBeGreaterThan(0.9);
      expect(n.freq[raise * H + kk], `KK at ${JSON.stringify(n.line)}`).toBeGreaterThan(0.6);
      if (n.actor === "BB") continue;
      const fold = n.options.findIndex((o) => o.action === "fold");
      expect(n.freq[fold * H + seven2], `72o at ${JSON.stringify(n.line)}`).toBeGreaterThan(0.9);
    }
    const bb = seats.indexOf("BB");
    for (let limper = 0; limper < seats.indexOf("SB"); limper += 1) {
      const line = vsLimp(limper, bb);
      if (!set.nodes.has(line)) continue;
      expect(share(set, line, ["check"]), `BB vs ${seats[limper]} limp`).toBeGreaterThan(0.6);
    }
  });

  it("never folds AA as the limper facing an isolation raise", () => {
    const aa = classByName("AA");
    for (const n of limpNodes.filter((n) => n.scenario === "vs-iso")) {
      const fold = n.options.findIndex((o) => o.action === "fold");
      expect(n.freq[fold * H + aa], JSON.stringify(n.line)).toBe(0);
    }
  });
});

describe("the sets against each other", () => {
  it("opens tighter from 9-max's early seats than from 6-max's first seat, and alike from the same distance", () => {
    for (const depth of [100, 150, 200]) {
      const six = chartSet(`nlhe-cash-6max-${depth}bb`);
      const nine = chartSet(`nlhe-cash-9max-${depth}bb`);
      const sixUtg = continues(six, "");
      for (const k of [0, 1, 2]) {
        expect(continues(nine, "f".repeat(k)), `9-max seat ${k} at ${depth}bb`).toBeLessThan(sixUtg);
      }
      // The LJ is three seats from the button, like 6-max's UTG.
      expect(Math.abs(continues(nine, "fff") - sixUtg), `LJ vs UTG at ${depth}bb`).toBeLessThan(0.04);
    }
  });

  it("records each depth's sizes: 2.2bb opens and 4-bets all-in past 40% of the stack at 40bb", () => {
    const short = chartSet("nlhe-cash-6max-40bb");
    const sizing = (short.model as Record<string, any>).tree.sizing;
    expect(sizing.open).toBe(2.2);
    expect(sizing.allInAbove).toBe(0.4);
    // Fold, limp (charts/4), open to 2.2bb.
    expect(short.nodes.get("")?.options.map((o) => o.toBb)).toEqual([0, 1, 2.2]);
    const vs3bet = [...short.nodes.values()].filter((n) => n.scenario === "vs-3bet");
    expect(vs3bet.length).toBeGreaterThan(5);
    // A 4-bet is all-in unless it stays under 16bb (2.2x an in-position 3-bet to 6.6 is 14.5).
    let shoves = 0;
    for (const n of vs3bet) {
      const raise = n.options.find((o) => o.action === "raise" || o.action === "allin");
      if (!raise) continue;
      if (raise.action === "allin") shoves += 1;
      else expect(raise.toBb, n.line).toBeLessThanOrEqual(16);
    }
    expect(shoves).toBeGreaterThan(vs3bet.length / 2);
    for (const id of ["nlhe-cash-6max-150bb", "nlhe-cash-9max-200bb"]) {
      const deep = chartSet(id);
      expect(deep.nodes.get("")?.options.map((o) => o.toBb)).toEqual([0, 1, 2.5]);
      // Deep, the 4-bet is a raise and only the 5-bet is all-in.
      const vs3bet = [...deep.nodes.values()].filter((n) => n.scenario === "vs-3bet" && !n.cold);
      expect(vs3bet.some((n) => n.options.some((o) => o.action === "raise"))).toBe(true);
    }
  });

  it("keeps the library small enough to load one set at a time", () => {
    const sizes = CHART_SETS.map((spec) => statSync(fileOf(spec.id)).size);
    expect(Math.max(...sizes)).toBeLessThan(9_000_000);
    expect(sizes.reduce((a, b) => a + b, 0)).toBeLessThan(40_000_000);
  });
});
