/**
 * Per-hand Open Graph tags for link-unfurl crawlers.
 *
 * A static SPA cannot set meta tags at request time, so `frontend/vercel.json`
 * rewrites `/h/:slug` to this function *only* when the User-Agent looks like a
 * crawler. Humans keep getting the SPA straight from the CDN, so this adds zero
 * latency to the normal path.
 *
 * The `shares` table is sealed — RLS on, no anon policies, no grants — so the
 * only read path is the `read_share` RPC, same as the browser uses.
 *
 * `read_share` is the read half of the pair introduced by
 * `20261003090000_share_projection.sql`; the counter lives in
 * `record_share_view`, which this function deliberately never calls. That split
 * is partly why it exists: the old combined `resolve_share` incremented `views`
 * on every read, so a single Slack paste could register dozens of "views" from
 * unfurl prefetches nobody ever looked at. A crawler is not a reader.
 *
 * `read_share` also returns an explicit projection rather than the `hands` row,
 * so nothing that reaches this edge function can contain `source_text`,
 * `owner_id` or `phf.meta.rawText` — worth knowing, because this function
 * renders its input into HTML that is served to the public.
 *
 * Everything here degrades: if the database is unreachable or the slug does not
 * exist, it still returns a valid 200 HTML document with the generic product
 * card rather than a broken unfurl.
 *
 * Env (Vercel project settings):
 *   SUPABASE_URL / VITE_SUPABASE_URL           required for per-hand tags
 *   SUPABASE_ANON_KEY / VITE_SUPABASE_ANON_KEY required for per-hand tags
 *   SITE_URL                                   optional, overrides the request origin
 *
 * NOTE: this file is not covered by `tsc -b` (tsconfig.app.json includes `src`
 * only). Vercel compiles it with esbuild.
 */

export const config = { runtime: "edge" };

const FALLBACK_TITLE = "Shared poker hand | Rail";
const FALLBACK_DESCRIPTION =
  "Replay a shared poker hand action by action, free and without an account, on Rail.";

/** The slice of `read_share`'s JSON this function reads. */
interface ResolvedShareJson {
  title?: string | null;
  /**
   * Whether this link's copy may reveal how the hand ended. Added by
   * `20261004120000_share_spoilers.sql`; **absent means false**, which is what
   * keeps a pre-migration database and a failed deploy both safe.
   */
  spoilers?: boolean | null;
  standardText?: string | null;
  phf?: {
    game?: {
      label?: string;
      smallBlind?: number;
      bigBlind?: number;
      unit?: { symbol?: string; minorUnits?: number };
    };
    players?: unknown[];
    results?: {
      totalPot?: number;
      wentToShowdown?: boolean;
      winners?: Array<{ player?: string; amount?: number }>;
    };
  } | null;
}

function env(...names: string[]): string | undefined {
  for (const name of names) {
    const value = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process
      ?.env?.[name];
    if (value) {
      return value;
    }
  }
  return undefined;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** PHF money is integer minor units; mirror `formatAmount()` from lib/phf/types. */
function money(amount: number | undefined, symbol = "$", minorUnits = 100): string {
  if (typeof amount !== "number" || Number.isNaN(amount)) {
    return "";
  }
  if (minorUnits <= 1) {
    return `${symbol}${amount}`;
  }
  const whole = amount / minorUnits;
  const text = whole % 1 === 0 ? String(whole) : whole.toFixed(2).replace(/0+$/, "").replace(/\.$/, "");
  return `${symbol}${text}`;
}

/**
 * Turns a resolved share into the two strings the crawler reads.
 *
 * ## The description does not say who won — #23
 *
 * This is the surface the bug lived on. Slack, Discord, Twitter and iMessage
 * all print `og:description` under the link, so `… · Villain wins $312 · shown
 * down` answered "what would you do here?" before a single reader opened the
 * post. The replayer's chrome had already been stripped of outcome data
 * (`fef6ff7`) and F3 turned that into a rule — `spoilersRevealed()` in
 * `tableMath.ts`, gating everything derived from `hand.results` on frame
 * position. An unfurl has no frame position: it is permanently at the deal. So
 * the same rule here reads `share.spoilers`, and the gate is closed unless the
 * sharer opened it.
 *
 * `spoilers !== true` rather than `=== false`, so a null column, a missing key,
 * a pre-migration database and a `read_share` that has not been redeployed all
 * fail *closed*. Leaking the result is the expensive direction of this mistake;
 * an over-cautious unfurl costs nothing.
 *
 * The stored `title` is also ignored when the gate is closed. It is not user
 * copy — every title in the table was generated by `buildSharePreview` — and
 * titles minted before this change end in `— $312 pot`, which is the same
 * disclosure one field over.
 */
function describe(share: ResolvedShareJson | null): { title: string; description: string } {
  if (!share) {
    return { title: FALLBACK_TITLE, description: FALLBACK_DESCRIPTION };
  }

  const spoilers = share.spoilers === true;
  const game = share.phf?.game;
  const results = share.phf?.results;
  const symbol = game?.unit?.symbol ?? "$";
  const minor = game?.unit?.minorUnits ?? 100;

  const stakes =
    game?.smallBlind !== undefined && game?.bigBlind !== undefined
      ? `${money(game.smallBlind, symbol, minor)}/${money(game.bigBlind, symbol, minor)}`
      : "";
  const label = (game?.label ?? "").replace(/\s*\([^)]*\)\s*$/, "");
  const pot = money(results?.totalPot, symbol, minor);
  const playerCount = share.phf?.players?.length;

  // With spoilers on, the stored label is already good copy. With them off it
  // cannot be trusted — see the note above — so the headline is rebuilt from
  // the three facts that are knowable before the first card.
  const tail = spoilers
    ? pot
      ? `— ${pot} pot`
      : ""
    : playerCount
      ? `— ${playerCount}-handed`
      : "";
  const derived = [stakes, label, tail].filter(Boolean).join(" ").trim();
  const fallback = derived ? `${derived} | Rail` : FALLBACK_TITLE;
  const title = spoilers ? share.title?.trim() || fallback : fallback;

  const bits: string[] = [];
  if (playerCount) {
    bits.push([`${playerCount}-handed`, stakes, label].filter(Boolean).join(" "));
  }
  // Read the board off the standard text rather than re-implementing runout
  // resolution here; the serializer always writes a single `Board [...]` line.
  // The board is the hand's *subject*, not its outcome, so it stays either way:
  // "board Ah Kd 7c" is what makes the question worth clicking on.
  const board = share.standardText?.match(/^Board \[([^\]]+)\]/m)?.[1];
  bits.push(board ? `board ${board}` : "no flop");

  if (spoilers) {
    // PHF lists one entry per collect per runout, so a split main/side pot shows
    // up as two rows for the same player. Sum before picking the biggest winner.
    const byPlayer = new Map<string, number>();
    for (const win of results?.winners ?? []) {
      if (win?.player) {
        byPlayer.set(win.player, (byPlayer.get(win.player) ?? 0) + (win.amount ?? 0));
      }
    }
    const winner = [...byPlayer.entries()].sort((a, b) => b[1] - a[1])[0];
    if (winner) {
      bits.push(`${winner[0]} wins ${money(winner[1], symbol, minor)}`.trim());
    }
    if (results?.wentToShowdown) {
      bits.push("shown down");
    }
  }
  bits.push("Replay it action by action on Rail.");

  return { title, description: bits.join(" · ") };
}

async function fetchShare(slug: string): Promise<ResolvedShareJson | null> {
  const baseUrl = env("SUPABASE_URL", "VITE_SUPABASE_URL");
  const anonKey = env("SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY");
  if (!baseUrl || !anonKey) {
    return null;
  }

  try {
    const response = await fetch(`${baseUrl.replace(/\/$/, "")}/rest/v1/rpc/read_share`, {
      method: "POST",
      headers: {
        apikey: anonKey,
        authorization: `Bearer ${anonKey}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({ p_slug: slug }),
      signal: AbortSignal.timeout(2500),
    });
    if (!response.ok) {
      return null;
    }
    return ((await response.json()) as ResolvedShareJson | null) ?? null;
  } catch {
    return null;
  }
}

function page(opts: { title: string; description: string; url: string; image: string }): string {
  const title = escapeHtml(opts.title);
  const description = escapeHtml(opts.description);
  const url = escapeHtml(opts.url);
  const image = escapeHtml(opts.image);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<meta name="description" content="${description}" />
<link rel="canonical" href="${url}" />
<meta property="og:type" content="article" />
<meta property="og:site_name" content="Rail" />
<meta property="og:title" content="${title}" />
<meta property="og:description" content="${description}" />
<meta property="og:url" content="${url}" />
<meta property="og:image" content="${image}" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${title}" />
<meta name="twitter:description" content="${description}" />
<meta name="twitter:image" content="${image}" />
<meta http-equiv="refresh" content="0; url=${url}" />
</head>
<body>
<p><a href="${url}">${title}</a></p>
</body>
</html>`;
}

export default async function handler(request: Request): Promise<Response> {
  const requestUrl = new URL(request.url);
  const slug =
    requestUrl.searchParams.get("slug") ?? requestUrl.pathname.split("/").filter(Boolean).pop() ?? "";

  const origin = env("SITE_URL")?.replace(/\/$/, "") ?? requestUrl.origin;
  const share = slug ? await fetchShare(slug) : null;
  const { title, description } = describe(share);

  return new Response(
    page({
      title,
      description,
      url: `${origin}/h/${encodeURIComponent(slug)}`,
      image: `${origin}/og-default.png`,
    }),
    {
      status: 200,
      headers: {
        "content-type": "text/html; charset=utf-8",
        // Crawlers re-fetch often; a short edge cache keeps the RPC quiet.
        "cache-control": "public, max-age=0, s-maxage=600, stale-while-revalidate=86400",
      },
    },
  );
}
